<p>
	<label for="<?= $fields["title"]["title"] ?>">
		<?= $fields["title"]["label"] ?>
	</label>
	<input class="widefat" id="<?= $fields["title"]["title"] ?>" name="<?= $fields["title"]["name"] ?>" type="<?= $fields["title"]["type"] ?>" value="<?= $fields["title"]["value"] ?>" />
</p>
<p>
	<label for="<?= $fields["featured_networks"]["title"] ?>">
		<?= $fields["featured_networks"]["label"] ?>
	</label>
	<input class="widefat" id="<?= $fields["featured_networks"]["title"] ?>" name="<?= $fields["featured_networks"]["name"] ?>" type="<?= $fields["featured_networks"]["type"] ?>" value="<?= $fields["featured_networks"]["value"] ?>" />
</p>
<p>
	<input class="widefat" id="<?= $fields["enable_toggle"]["title"] ?>" name="<?= $fields["enable_toggle"]["name"] ?>" type="<?= $fields["enable_toggle"]["type"] ?>" value="<?= $fields["enable_toggle"]["value"] ?>" <?= $fields["enable_toggle"]["checked"] ?>/>
	<label for="<?= $fields["enable_toggle"]["title"] ?>">
		<?= $fields["enable_toggle"]["label"] ?>
	</label>
</p>
<p>
	<label for="<?= $fields["toggle_networks"]["title"] ?>">
		<?= $fields["toggle_networks"]["label"] ?>
	</label>
	<input class="widefat" id="<?= $fields["toggle_networks"]["title"] ?>" name="<?= $fields["toggle_networks"]["name"] ?>" type="<?= $fields["toggle_networks"]["type"] ?>" value="<?= $fields["toggle_networks"]["value"] ?>" />
</p>